# name: Waka Readme

# on:
#   schedule:
#     - cron: '0 0 * * *'
#   workflow_dispatch:

# jobs:
#   update-readme:
#     name: Update Readme with Metrics
#     runs-on: ubuntu-latest
#     steps:
#       - uses: anmol098/waka-readme-stats@master
#         with:
#           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
#           GH_TOKEN: ${{ secrets.GH_TOKEN }}
#           # 时间线
#           SHOW_LOC_CHART: False
#           SHOW_LINES_OF_CODE: False
#           SHOW_TOTAL_CODE_TIME: False
#           SHOW_PROFILE_VIEWS: False
#           SHOW_SHORT_INFO: False
          
#           SHOW_LANGUAGE: False
#           SHOW_PROJECTS: False
#           SHOW_OS: False
#           SHOW_TIMEZONE: False
#           SHOW_EDITORS: False
          
          
#           SHOW_DAYS_OF_WEEK: False

          
